import { useEffect, useState } from "react";

type Role = { id: string; name: string; description: string; profile: { profile: string; personality: string; behaviorRules: string; responseConstraints: string; nickname: string }; createdAt: string; updatedAt: string };
const empty = { name: "", description: "", profile: "", personality: "", behaviorRules: "", responseConstraints: "", nickname: "" };
const api = async (path: string, init?: RequestInit) => { const response = await fetch(path, { headers: { "content-type": "application/json" }, ...init }); const data = await response.json(); if (!response.ok) throw new Error(data.detail ?? data.error ?? "请求失败"); return data; };

export function App() {
  const [roles, setRoles] = useState<Role[]>([]); const [selected, setSelected] = useState<Role | null>(null); const [draft, setDraft] = useState(empty); const [creating, setCreating] = useState(false); const [error, setError] = useState("");
  const refresh = async () => { const data = await api("/api/roles"); setRoles(data.roles); };
  useEffect(() => { void refresh().catch((cause) => setError(cause.message)); }, []);
  const edit = (role: Role) => { setSelected(role); setCreating(false); setDraft({ name: role.name, description: role.description, ...role.profile }); };
  const save = async (event: React.FormEvent) => { event.preventDefault(); setError(""); try { const payload = { name: draft.name, description: draft.description, profile: { profile: draft.profile, personality: draft.personality, behaviorRules: draft.behaviorRules, responseConstraints: draft.responseConstraints, nickname: draft.nickname } }; const data = creating ? await api("/api/roles", { method: "POST", body: JSON.stringify(payload) }) : await api(`/api/roles/${encodeURIComponent(selected!.id)}`, { method: "PUT", body: JSON.stringify(payload) }); await refresh(); edit(data.role); } catch (cause) { setError(cause instanceof Error ? cause.message : "保存失败"); } };
  return <main><header><h1>角色</h1><button onClick={() => { setCreating(true); setSelected(null); setDraft(empty); }}>创建角色</button></header><div className="layout"><aside>{roles.map((role) => <button className={selected?.id === role.id ? "active" : ""} key={role.id} onClick={() => edit(role)}><strong>{role.name}</strong><span>{role.description || "暂无简介"}</span><small>{role.id}</small></button>)}{!roles.length && <p>还没有角色。</p>}</aside><section>{(creating || selected) ? <form onSubmit={save}><h2>{creating ? "创建角色" : "角色详情"}</h2>{error && <p className="error">{error}</p>}<label>名称<input value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })}/></label><label>简介<textarea value={draft.description} onChange={(e) => setDraft({ ...draft, description: e.target.value })}/></label><label>角色设定<textarea required value={draft.profile} onChange={(e) => setDraft({ ...draft, profile: e.target.value })}/></label><label>性格<textarea value={draft.personality} onChange={(e) => setDraft({ ...draft, personality: e.target.value })}/></label><label>行为规则<textarea value={draft.behaviorRules} onChange={(e) => setDraft({ ...draft, behaviorRules: e.target.value })}/></label><label>回复约束<textarea value={draft.responseConstraints} onChange={(e) => setDraft({ ...draft, responseConstraints: e.target.value })}/></label><label>昵称<input value={draft.nickname} onChange={(e) => setDraft({ ...draft, nickname: e.target.value })}/></label><button type="submit">保存</button></form> : <p>选择角色或创建新角色。</p>}</section></div></main>;
}
